services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - ai-app-network

networks:
  ai-app-network:
    driver: bridge
